version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies from our offline mirror
          command: yarn install --offline
      - run:
          name: Run all Continuous Integration checks
          command: yarn ci-check
      - deploy:
          name: deploy to IBM Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Install `ibmcloud` CLI
              curl -fsSL https://clis.ng.bluemix.net/install/linux | sh

              # Login and install blue-green-deploy plugin
              ibmcloud login \
                -a 'https://cloud.ibm.com' \
                -r 'us-south' \
                --apikey "$CLOUD_API_KEY"
              ibmcloud target -o carbon-design-system -s production
              ibmcloud cf install -v 6.50.0
              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              # Build default storybook
              yarn build:storybook --quiet

              # Use blue-green-deploy for our buildpack
              ibmcloud cf blue-green-deploy carbon-storybook-vue \
                -f .circleci/manifest.yml \
                --delete-old-apps
            fi
